### PR TITLE
MVP: tfp-automation

### PR DESCRIPTION
**Pull request by Josh-Diamond**
meets MVP requirements for https://github.com/rancher/qa-tasks/issues/386

### CODE REVIEW

**Review by markusewalker — APPROVED** [review]
LGTM. Jenkins integration is already working, so next steps after this is merged is updating personal repo to this official repo, which will be in a follow-up PR.

**Review by brudnak — APPROVED** [review]
lgtm

**Review by slickwarren — APPROVED** [review]
lgtm

**Review by igomez06 — APPROVED** [review]
Looks good Josh, just an FYI once we move the framework your go.mod file will change.

**Pull request merged**
